/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingsIndexRouteImport } from './routes/rankings/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as RankingsManageRouteImport } from './routes/rankings/manage'
import { Route as RankingsYearRouteImport } from './routes/rankings/$year'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsManageRoute = RankingsManageRouteImport.update({
  id: '/rankings/manage',
  path: '/rankings/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsYearRoute = RankingsYearRouteImport.update({
  id: '/rankings/$year',
  path: '/rankings/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/admin/users': typeof AdminUsersRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/rankings/$year': typeof RankingsYearRoute
  '/rankings/manage': typeof RankingsManageRoute
  '/games': typeof GamesIndexRoute
  '/rankings': typeof RankingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/admin/users': typeof AdminUsersRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/rankings/$year': typeof RankingsYearRoute
  '/rankings/manage': typeof RankingsManageRoute
  '/games': typeof GamesIndexRoute
  '/rankings': typeof RankingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/admin/users': typeof AdminUsersRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/rankings/$year': typeof RankingsYearRoute
  '/rankings/manage': typeof RankingsManageRoute
  '/games/': typeof GamesIndexRoute
  '/rankings/': typeof RankingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/results'
    | '/admin/users'
    | '/games/$gameId'
    | '/games/new'
    | '/invite/$token'
    | '/rankings/$year'
    | '/rankings/manage'
    | '/games'
    | '/rankings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/results'
    | '/admin/users'
    | '/games/$gameId'
    | '/games/new'
    | '/invite/$token'
    | '/rankings/$year'
    | '/rankings/manage'
    | '/games'
    | '/rankings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/results'
    | '/admin/users'
    | '/games/$gameId'
    | '/games/new'
    | '/invite/$token'
    | '/rankings/$year'
    | '/rankings/manage'
    | '/games/'
    | '/rankings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesNewRoute: typeof GamesNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RankingsYearRoute: typeof RankingsYearRoute
  RankingsManageRoute: typeof RankingsManageRoute
  GamesIndexRoute: typeof GamesIndexRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/manage': {
      id: '/rankings/manage'
      path: '/rankings/manage'
      fullPath: '/rankings/manage'
      preLoaderRoute: typeof RankingsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$year': {
      id: '/rankings/$year'
      path: '/rankings/$year'
      fullPath: '/rankings/$year'
      preLoaderRoute: typeof RankingsYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  AdminUsersRoute: AdminUsersRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GamesNewRoute: GamesNewRoute,
  InviteTokenRoute: InviteTokenRoute,
  RankingsYearRoute: RankingsYearRoute,
  RankingsManageRoute: RankingsManageRoute,
  GamesIndexRoute: GamesIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
